name: base
channels:
  - conda-forge
dependencies:
  # ------------------------------------------------------------------------- Non-Python {{{1
  - nodejs
  - ffmpeg
  # Don't install Pandoc explicitly, at least until it becomes available on ARM-based
  # macOS. On Linux, it will still be installed as a dependency of JupyterLab.
  # ----------------------------------------------------------------------------- Python {{{1
  # basics
  - pynvim
  - ipython
  - ipdb
  - black
  - rich
  # stdlib replacements
  - lxml
  - regex
  - httpx
  # Jupyter
  - jupyterlab
  - jupytext
  # data analysis
  - pandas
  - scikit-learn
  - statsmodels
  - altair
  - matplotlib
  - seaborn
  # optional Pandas deps
  - sqlalchemy
  - mysqlclient
  - openpyxl
  # CLI tools
  - tldr
